### PR TITLE
Fixed memory leaks with non processed TPerIoData

### PR DESCRIPTION
**Pull request by viniciusfbb**
In TIocpCrossSocket destructor, the ProcessIoEvent can receive a SHUTDOWN_FLAG before others PerIoData, and they aren't released because after SHUTDOWN_FLAG, the ProcessIoEvent will not be called again to process they. I don't know what is the best way to fix this but here is an workaround.

Example of leak: (calling the connect and then destroying without delay)

```
var
  LCrossSocket: ICrossSocket;
begin
  LCrossSocket := TCrossSocket.Create(1);
  LCrossSocket.Connect('127.0.0.1', 6900);
end;
```

### CODE REVIEW

**Comment by winddriver** [comment]
I don't think it is necessary to consider this extreme situation, because it is unlikely to release the ICrossSocket immediately after it is created. If you try Sleep(1000) after Connect, you will find that ProcessIoEvent will be notified of the Connect failure.

**Comment by viniciusfbb** [comment]
Souledge, this error is not only for Connect, it also occurs in Send, and in this case is more serious because the TPerIoData.CrossData references the ICrossConnection, that is, the connection is not destroyed either. This is not unusual because in my case, for example, my app has a request response class, which is called several times, creating a CrossSocket for each, and having an X timeout, that is, has X seconds to connect, send and receive, but always when you give the timeout and finish the CrossSocket, the leaks occur because there are some TPerIoData to be processed.

**Comment by viniciusfbb** [comment]
@winddriver, Souledge, you were right, my first solution was very bad, because it lost a lot of performance and had some problems.
But I've found a much simpler solution that does not compromise performance at all and works fully. See the changes again.

**Comment by winddriver** [comment]
Thank you for your continuous follow - up. I made some minor changes to your patch and submitted it

**Pull request closed without merging**
